server:
  port: 8084

spring:
  application:
    name: WeChatOfficialAccounts
  datasource:
    url: jdbc:mysql://127.0.0.1/official-accounts?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #  create 启动时删数据库中的表，然后创建，退出时不删除数据表
    #  create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
    #  update 如果启动时表格式不一致则更新表，原有数据保留
    #  validate 项目启动表结构进行校验 如果不一致则报错
    show-sql: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://system-server-1:8761/eureka/

we-chat:
  app-id: a
  app-secret: 1
  # access_token get
  access-token-url-get: https://api.weixin.qq.com/cgi-bin/token
