server:
  port: 8081
spring:
  application:
    name: sercurity
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/system?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #  create 启动时删数据库中的表，然后创建，退出时不删除数据表
    #  create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
    #  update 如果启动时表格式不一致则更新表，原有数据保留
    #  validate 项目启动表结构进行校验 如果不一致则报错
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

